"""
TransferRecord — tracks the full lifecycle of a warm transfer attempt.

Each transfer attempt (AI → manager) creates one TransferRecord.
Immutable history: never deleted. Status transitions are append-only via field updates.

Transfer flow:
  INITIATED → CALLING_MANAGER → BRIEFING → CONNECTED
                                          ↘ FAILED_NO_ANSWER
  INITIATED → FAILED_ALL_UNAVAILABLE   (when no managers found)
"""
from __future__ import annotations

import enum
import uuid
from typing import Optional, TYPE_CHECKING

from sqlalchemy import ForeignKey, Index, Integer, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.call import Call
    from app.models.manager import Manager


class TransferStatus(str, enum.Enum):
    INITIATED = "INITIATED"                         # Transfer request received
    CALLING_MANAGER = "CALLING_MANAGER"             # Dialling manager phone
    BRIEFING = "BRIEFING"                           # Manager answered, whisper playing
    CONNECTED = "CONNECTED"                         # Customer bridged to manager ✅
    FAILED_NO_ANSWER = "FAILED_NO_ANSWER"           # All managers tried — none answered
    FAILED_ALL_UNAVAILABLE = "FAILED_ALL_UNAVAILABLE"  # No managers available at all
    CALLER_DROPPED = "CALLER_DROPPED"               # Client hung up during transfer ❌
    BRIDGE_FAILED = "BRIDGE_FAILED"                 # Manager answered, but bridge failed ❌
    TIMED_OUT = "TIMED_OUT"                         # Timeout at some transfer stage ❌


TERMINAL_TRANSFER_STATUSES = frozenset({
    TransferStatus.CONNECTED,
    TransferStatus.FAILED_NO_ANSWER,
    TransferStatus.FAILED_ALL_UNAVAILABLE,
    TransferStatus.CALLER_DROPPED,
    TransferStatus.BRIDGE_FAILED,
    TransferStatus.TIMED_OUT,
})


class TransferRecord(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "transfer_records"

    call_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("calls.id"), nullable=False
    )
    # Manager selected for this transfer attempt (null before selection)
    manager_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid, ForeignKey("managers.id"), nullable=True
    )
    status: Mapped[TransferStatus] = mapped_column(
        String(30), nullable=False, default=TransferStatus.INITIATED
    )

    # Generated by SummaryService — 5-field structured text shown to manager
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Short ≤200 char brief played as audio before customer is bridged
    whisper_text: Mapped[Optional[str]] = mapped_column(String(250), nullable=True)

    # Engine-assigned call leg ID for the manager-side call (from TransferEngine)
    manager_call_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # How many dial attempts were made (incremented on each retry)
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Department filter used at initiation time — stored for audit
    department: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Human-readable note on failure — shown in bot card
    fallback_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Machine-readable failure stage for observability:
    # "no_managers" | "dial" | "briefing" | "bridge" | "caller_dropped" | "timeout"
    failure_stage: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)

    call: Mapped["Call"] = relationship("Call", back_populates="transfer_records")
    manager: Mapped[Optional["Manager"]] = relationship("Manager")

    __table_args__ = (
        Index("ix_transfer_records_call_id", "call_id"),
        Index("ix_transfer_records_status", "status"),
    )

    def __repr__(self) -> str:
        return (
            f"<TransferRecord call={self.call_id} "
            f"status={self.status} manager={self.manager_id}>"
        )
